apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  amiFamily: AL2023
  role: eks-nodegroup
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  tags:
    karpenter.sh/discovery: {{ .Values.clusterName }}
  amiSelectorTerms:
    - id: {{ .Values.amiId }} # x86_64